#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"; IMAGE="dokku/$APP"
echo "-----> Checking for pre-build script"
if [ -f "hooks/pre-build" ]; then
    echo "=====> Running pre-build script"
    COMMAND=$(cat hooks/pre-build <<EOF
sleep 1 # wait so that docker run has not exited before docker attach
EOF
)
    id=$(docker run -d $IMAGE /bin/bash -e -c "$COMMAND")
    #enable logs
    docker logs -f $id
    test $(docker wait $id) -eq 0
    docker commit $id $IMAGE > /dev/null
    echo "=====> End of pre-build script"
fi
