#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1";
echo "-----> Checking for pre-build script"
if [ -f "hooks/pre-build" ]; then
    if [ ! -x "hooks/pre-build" ]; then
        echo " !     Adding missing execution permission. Please change the permission on your codebase." 1>&2
        chmod +x hooks/pre-build
    fi
    echo "=====> Running pre-build script"
    hooks/pre-build
    echo "=====> End of pre-build script"
fi
